Browser=chrome
url=https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
user=Admin
pass=admin123
firstName=mahammed
middleName=tousif
lastname=phatan
email=mohammedtousif3709@gmail.com
contactNumber=9980665378
keyword=hello word
notes=Hello word
CadidateName=mahammed